CREATE TABLE noteful_notes (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  note_name TEXT NOT NULL,
  modified TIMESTAMPTZ NOT NULL DEFAULT now(),
  folderId INTEGER REFERENCES noteful_folders(id),
  content TEXT
);

